languageCode = "en-us"
title = "Massively"
baseURL = "https://gazslum.netlify.com/"
theme = "."
googleanalytics = "UA-113904582-3"
disqusShortname = "hugo-massively"

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
# [params.posts]
#     foldername = "post"
#     pagesize = "6"
#     featuredpost = "true"

[languages]
[languages.en]
  languageName = "English"
[languages.es]
  languageName = "Español"
  title = "Escuela del Artes Calle - Versión Español"
[languages.fr]
  languageName = "Français"
  title = "L'école d'art des rues - Version Française"
