languageCode = "en-us"
title = "Gaz Street Art"
baseURL = "https://nifty-bartik-ad3653.netlify.com/"
theme = "."
googleanalytics = ""
disqusShortname = "gazslum"

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
# [params.posts]
#     foldername = "post"
#     pagesize = "6"
#     featuredpost = "true"

[languages]
[languages.en]
  languageName = "English"
[languages.es]
  languageName = "Español"
  title = "Escuela del Artes Calle - Versión Español"
# [languages.fr]
#  languageName = "Français"
#  title = "L'école d'art des rues - Version Française"
